Traceback (most recent call last):
  File "/home/mpagani/code/others/taskmaster/script/http_server.py", line 17, in <module>
    httpd = HTTPServer(server_address, CustomHandler)
  File "/usr/lib/python3.10/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/lib/python3.10/http/server.py", line 137, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.10/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
127.0.0.1 - - [27/Jun/2024 16:16:08] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [27/Jun/2024 16:16:08] "GET /favicon.ico HTTP/1.1" 200 -
127.0.0.1 - - [27/Jun/2024 16:16:37] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [27/Jun/2024 16:16:37] "GET /favicon.ico HTTP/1.1" 200 -
127.0.0.1 - - [27/Jun/2024 16:16:38] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [27/Jun/2024 16:16:39] "GET /favicon.ico HTTP/1.1" 200 -
127.0.0.1 - - [27/Jun/2024 16:16:43] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [27/Jun/2024 16:16:44] "GET /favicon.ico HTTP/1.1" 200 -
Traceback (most recent call last):
  File "/home/mpagani/code/others/taskmaster/script/http_server.py", line 17, in <module>
    httpd = HTTPServer(server_address, CustomHandler)
  File "/usr/lib/python3.10/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/lib/python3.10/http/server.py", line 137, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.10/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/mpagani/code/others/taskmaster/script/http_server.py", line 17, in <module>
    httpd = HTTPServer(server_address, CustomHandler)
  File "/usr/lib/python3.10/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/lib/python3.10/http/server.py", line 137, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.10/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
127.0.0.1 - - [27/Jun/2024 16:17:23] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [27/Jun/2024 16:17:23] "GET /favicon.ico HTTP/1.1" 200 -
127.0.0.1 - - [27/Jun/2024 16:17:24] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [27/Jun/2024 16:17:24] "GET /favicon.ico HTTP/1.1" 200 -
127.0.0.1 - - [27/Jun/2024 16:17:24] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [27/Jun/2024 16:17:24] "GET /favicon.ico HTTP/1.1" 200 -
127.0.0.1 - - [27/Jun/2024 16:17:25] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [27/Jun/2024 16:17:25] "GET /favicon.ico HTTP/1.1" 200 -
Terminated
127.0.0.1 - - [27/Jun/2024 16:18:53] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [27/Jun/2024 16:18:53] "GET /favicon.ico HTTP/1.1" 200 -
Traceback (most recent call last):
  File "/home/mpagani/code/others/taskmaster/script/http_server.py", line 17, in <module>
    httpd = HTTPServer(server_address, CustomHandler)
  File "/usr/lib/python3.10/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/lib/python3.10/http/server.py", line 137, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.10/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/mpagani/code/others/taskmaster/script/http_server.py", line 17, in <module>
    httpd = HTTPServer(server_address, CustomHandler)
  File "/usr/lib/python3.10/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/lib/python3.10/http/server.py", line 137, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.10/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
127.0.0.1 - - [27/Jun/2024 17:17:45] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [27/Jun/2024 17:17:46] "GET /favicon.ico HTTP/1.1" 200 -
127.0.0.1 - - [27/Jun/2024 17:18:23] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [27/Jun/2024 17:18:23] "GET /favicon.ico HTTP/1.1" 200 -
127.0.0.1 - - [27/Jun/2024 17:19:10] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [27/Jun/2024 17:19:10] "GET /favicon.ico HTTP/1.1" 200 -
Traceback (most recent call last):
  File "/home/mpagani/code/others/taskmaster/script/http_server.py", line 17, in <module>
    httpd = HTTPServer(server_address, CustomHandler)
  File "/usr/lib/python3.10/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/lib/python3.10/http/server.py", line 137, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.10/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
127.0.0.1 - - [27/Jun/2024 17:19:30] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [27/Jun/2024 17:19:30] "GET /favicon.ico HTTP/1.1" 200 -
127.0.0.1 - - [27/Jun/2024 17:19:31] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [27/Jun/2024 17:19:31] "GET /favicon.ico HTTP/1.1" 200 -
127.0.0.1 - - [27/Jun/2024 17:19:31] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [27/Jun/2024 17:19:31] "GET /favicon.ico HTTP/1.1" 200 -
Killed
127.0.0.1 - - [27/Jun/2024 17:26:53] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [27/Jun/2024 17:26:53] "GET /favicon.ico HTTP/1.1" 200 -
127.0.0.1 - - [27/Jun/2024 17:27:15] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [27/Jun/2024 17:27:16] "GET /favicon.ico HTTP/1.1" 200 -
127.0.0.1 - - [27/Jun/2024 17:27:16] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [27/Jun/2024 17:27:16] "GET /favicon.ico HTTP/1.1" 200 -
127.0.0.1 - - [27/Jun/2024 17:27:17] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [27/Jun/2024 17:27:17] "GET /favicon.ico HTTP/1.1" 200 -
127.0.0.1 - - [27/Jun/2024 17:30:23] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [27/Jun/2024 17:30:23] "GET /favicon.ico HTTP/1.1" 200 -
127.0.0.1 - - [27/Jun/2024 17:30:24] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [27/Jun/2024 17:30:24] "GET /favicon.ico HTTP/1.1" 200 -
127.0.0.1 - - [27/Jun/2024 17:30:24] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [27/Jun/2024 17:30:24] "GET /favicon.ico HTTP/1.1" 200 -
127.0.0.1 - - [27/Jun/2024 17:42:22] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [27/Jun/2024 17:42:22] "GET /favicon.ico HTTP/1.1" 200 -
Traceback (most recent call last):
  File "/home/mpagani/code/others/taskmaster/script/http_server.py", line 17, in <module>
    httpd = HTTPServer(server_address, CustomHandler)
  File "/usr/lib/python3.10/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/lib/python3.10/http/server.py", line 137, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.10/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
127.0.0.1 - - [27/Jun/2024 17:43:38] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [27/Jun/2024 17:43:38] "GET /favicon.ico HTTP/1.1" 200 -
127.0.0.1 - - [27/Jun/2024 17:44:34] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [27/Jun/2024 17:44:34] "GET /favicon.ico HTTP/1.1" 200 -
Traceback (most recent call last):
  File "/home/mpagani/code/others/taskmaster/script/http_server.py", line 17, in <module>
    httpd = HTTPServer(server_address, CustomHandler)
  File "/usr/lib/python3.10/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/lib/python3.10/http/server.py", line 137, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.10/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/mpagani/code/others/taskmaster/script/http_server.py", line 17, in <module>
    httpd = HTTPServer(server_address, CustomHandler)
  File "/usr/lib/python3.10/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/lib/python3.10/http/server.py", line 137, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.10/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
127.0.0.1 - - [27/Jun/2024 18:18:29] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [27/Jun/2024 18:18:30] "GET /favicon.ico HTTP/1.1" 200 -
127.0.0.1 - - [27/Jun/2024 18:19:28] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [27/Jun/2024 18:19:28] "GET /favicon.ico HTTP/1.1" 200 -
Traceback (most recent call last):
  File "/home/mpagani/code/others/taskmaster/script/http_server.py", line 17, in <module>
    httpd = HTTPServer(server_address, CustomHandler)
  File "/usr/lib/python3.10/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/lib/python3.10/http/server.py", line 137, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.10/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/mpagani/code/others/taskmaster/script/http_server.py", line 17, in <module>
    httpd = HTTPServer(server_address, CustomHandler)
  File "/usr/lib/python3.10/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/lib/python3.10/http/server.py", line 137, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.10/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/mpagani/code/others/taskmaster/script/http_server.py", line 17, in <module>
    httpd = HTTPServer(server_address, CustomHandler)
  File "/usr/lib/python3.10/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/lib/python3.10/http/server.py", line 137, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.10/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/mpagani/code/others/taskmaster/script/http_server.py", line 17, in <module>
    httpd = HTTPServer(server_address, CustomHandler)
  File "/usr/lib/python3.10/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/lib/python3.10/http/server.py", line 137, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.10/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
127.0.0.1 - - [27/Jun/2024 18:42:26] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [27/Jun/2024 18:42:26] "GET /favicon.ico HTTP/1.1" 200 -
127.0.0.1 - - [27/Jun/2024 18:43:17] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [27/Jun/2024 18:43:17] "GET /favicon.ico HTTP/1.1" 200 -
